sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-subscription-plugin
    all_branches: true
env:
  global:
  - secure: NnmRc/0vCP7z+t+1c67M4sAmgfwaQNHFAIAKGcFrBZH2RrEbzJMKfEKw5EAhhDWxH0UbRqAcS8SCn24TewWfBPv72x1e+Pp+v6p2wGefcjoxM0W0RfMp/nzlJw/gdwZr6CdP58TzwRlYV+rum4EUMfP4vSEd0wSi4p0QtaHurhGqd/haDHeBC4b+ilvLG/8FksA2CEHNIzQ9zwHUVLwqNGE+9cZmQXu0FMGcOPTJGA0YZ7An0nJoHgfywSqvebbZV7azGOYkaQJxEtq/lDdRG+79qGHbs/3Rs7QIduBAEtfFYUk3LNI4KqRDNu9RNnO+57CgfkmExFqw6IIQBTxJVrkUSLm31T7qpy9WqLZnjM5TZ2ryzlG0J1dcsLSVuRA6XkPEdXWOy9wB0qPuMBV0a/dnl7pq6pIbqhN00sMdZzSdxCxibhzDKtR4nAvJeyGkCMcNEY0FOqry6iByrPfOutHiUQgWM2r26XnFnR7wbY1ZzX6bykqKrKkah0Joh7TcsM6SPvhQqFObc3fGbPLCIPlQ5+kse5LrK4MRhqjHL2Ky2riW1s7yVw4NLoRDy4I9z/n83EyAAhE05RtRiO/DvzVU2BemQHoM4LW4Sfb4VtCY8aum6cb3j1cyE26Hl3l4Ov2NpXX4QKnMKovp3+eIPH4LM8UZfZhRsGwyj5t0IhI=
  - secure: YmJWmEKYufzmG8uMa4PKtk2dCHZ5j+tSW+/pqOKVbx8yp1ch07e2m6kccPxUCtH5fogm8hJiyN4fPBYikZ50kDEH34yNPZYl5/nZP8qt0szIpb36l7ZuzrJS5Zq2SuRoXJdEG9EuSfv6PAPc4IbksIYs3hDXetbGsp1GsZl/C1ULNaFjQxV+kabnw/780uWr+/KDKej69K7A+v5B2HF82G+RbsR7o6OFDNVrpCvO64LnOfUfTyjz4eD/5jBiI1uLYkeNy6KLueHW1XKvZCKWWiueJkXgLe/WXTGtqBzSm1sfOlHhf2kl83YkYoQbDhkbHyqmuVYiU6xXuETDhufORZ39BxWnl4LWXhPJBUr/iqKEqIys98unFL7wQ9drOC7Eeti2FiiTwMopXP7UfksBVKHDVBnfMliwQZVvIUn+Jl+N7T7FoMKpskX7rGazp0oJUAzmtjupENMYQaukMEAueN9AwrlmHVzI3I3nFKJG8jfgiSDNBw4oyv3nCZu0SU5kUSyuSQU+yjQo9uP/XAkm/NyyYxRo9gQzne5WXyx4GnYJlPqS99Nb1EURqi1oBFa+KAybLuqZPc712DbdIW+3HbAHkkzgu/xNb0sJ2cOz/r7yCBDc94a7KYlk7cBkF0REjyq1A/WmFxaNeEnCFXPAep5U/tJMIHnJwpNOaDeLAn4=
